%% Response Adjustment to Initial Response Populations Generated by Hybrid Environmental Change Response Strategies
function Population=Response_adjust(Problem,Population,W,N,lower,upper)
    % Individual transfer adjustment
     F=0.8; 
    [FrontNo,~] = NDSort(Population.objs,Population.cons,N);
    Non_domain_index=find(FrontNo==1);
    Domain_index=find(FrontNo~=1);
    size1=length(Non_domain_index);
    if(size1<N)
        for i=1:length(Domain_index)
             r_index=randperm(length(Non_domain_index),1);
             new_one_dec=Population(Domain_index(i)).dec+F*(Population(Non_domain_index(r_index)).dec-Population(Domain_index(i)).dec)+normrnd(0,0.2);
             new_one_dec= min(max(new_one_dec,lower),upper);
             new_one=Problem.Evaluation(new_one_dec);
             Population(Domain_index(i))=new_one;
        end
    end 
    
    % Vector matching adjustment
     Population=Vector_matching(Population,W);
end